#! /usr/bin/env python3
import os
import sys

try:
    command = sys.argv[1]
except IndexError:
    print("No command entered. " +
          "Type 'feedme help' for a list of commands.")
    quit()

valid = ['help']

if command in valid:
    if command == 'help':
        print("No commands yet bb")
else:
    print("Invalid command. Type 'feedme help' for a list of commands.")
